# Generated by Django 2.2.3 on 2019-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='border',
            name='photo',
            field=models.ImageField(default='config/static/no_image.png', upload_to='config/static'),
        ),
        migrations.AlterField(
            model_name='border',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
